CREATE TABLE [dbo].[Profile]
(
	[ID] NVARCHAR(255) NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(255) NOT NULL,
	[Email] NVARCHAR(255) NOT NULL,
	[DOB] DATE NOT NULL,
	[Role] NVARCHAR(255) NULL,
	[ProfileImage] NVARCHAR(255) NULL
)
